#!/bin/sh
# Start/stop dataDrill.

case "$1" in
  start)
    echo "Starting dataDrill"
    cd /home/dataDrill # Change to the intended directory
    ./dataDrill & # Run dataDrill from the intended directory
    ;;
  stop)
    echo "Stopping dataDrill"
    pkill -f dataDrill
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
